# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    - target/ng-spring-boot.jar
# optional list of port to expose on the host
ports:
  - 40080
healthChecks:
  pings:
    - url: http://localhost:40080/actuator/health
      timeout: 80000
# how long in milliseconds to sleep after start-up (default 0)
sleep: 5000
# tag to use for images
tag: demo/app:ng-spring-boot-${project.version}